language: c
compiler: gcc
sudo: required
dist: xenial
cache:
  - apt
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential automake autopoint autoconf libtool pkg-config intltool autoconf-archive libpcre3-dev libglib2.0-dev libgtk-3-dev libxml2-utils
script:
  - ./autogen.sh
  - ./configure
  - make
